name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Swift Tests
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04-arm
            container: swift:6.1.0
          - os: macos-15
            xcode-select: /Applications/Xcode_16.3.app

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: xcode-select
        if: ${{ matrix.xcode-select != '' }}
        run: |
          sudo xcode-select --switch ${{ matrix.xcode-select }}

      - name: Build
        run: swift build

      - name: Run Tests
        run: swift test
